### ISSUE TITLE
Add DC to simple progression with attached stat.

### ISSUE THREAD

**Issue by Bogus73** [crash1115/5e-training#16]
Hi, 
I have a player who found a book of knowledge that she can unlock in stages. This would be the perfect thing to do with your module.

What I would like to do is the following.

Set number of checks (not rolled stats like 16 int check until 200 or so) in my case she has to do 6 checks with changing DCs to successfully unlock the tome.

stage 1 2 DC 10 Int checks
stage 2 2 DC 15 Int checks
stage 3 2 DC 20 Int checks

I would love to track successes and failures of the check in the training tabs.

So I would know what she successfully unlocked.

Thanks for your hard work. Keep going!

**Comment by crash1115** [comment]
This is really interesting! I can probably implement the DC's without too much difficulty, but stages will require a bit of an overhaul, so that'll come a little later. I'll shoot for v0.4.0 with the DC's (hopefully this weekend or next, depending on how much time I have) and try to figure out the best way to implement stages once I have some time to think about the best way to accomplish it. Stages with different progression types is something I was looking at a while back, so I'll definitely get to it at some point.

If you need a way to track this in the meantime, you can set up a series of Simple progression activities like this:
`Name: Stage 1, Attempts: 2`
`Name: Stage 2, Attempts: 2`
`Name: Stage 3, Attempts: 2`
Then have her roll the checks manually and if they succeed, have her add a success to the appropriate stage.

Thanks for the suggestion!

**Comment by Bogus73** [comment]
Cool that it will come in the future and I will use the workaround you suggested for the moment.
