### ISSUE TITLE
Add the possibility of a naked d20, d100, etc. roll

### ISSUE THREAD

**Issue by turboraton** [crash1115/5e-training#25]
Hey there Crash! REALLY NICE module, I believe it would be great if you also just add a naked roll to downtime activities.

**Comment by crash1115** [comment]
Yeah, absolutely! I'll get it done for 0.5.0, possibly sometime this week depending on how much free time I have.

If you need a workaround until I can get it released - you can set up a Simple activity, then do your roll separately and just update the progress on the activity based on the roll manually. :+1:

**Comment by crash1115** [comment]
As of 0.5.0, you can set up activities to run macros. These can be used to non skill/tool/ability/simple rolls.

If you need help with a macro, feel free to tag me on Discord and I'll help you out. Otherwise there's some simple API docs at the bottom of the readme, and an example of a simple macro [here](https://github.com/crash1115/5e-training/blob/master/examples.md#increase-by-1d20-macro) that quite literally just rolls a d20 and adds it to the progress value.
