### ISSUE TITLE
Support for MyBeyond - D&D 5e Character Sheet Theme

### ISSUE THREAD

**Issue by kaihangaverdener** [crash1115/5e-training#36]
Thanks for creating this module. It looks very useful.

When using the MyBeyond - D&D 5e Character Sheet Theme module, the Change Log and Add buttons are missing from the Downtime tab. Also, if I switch to a different sheet, add an activity and switch back, the activity tab is blank.

I could not see a way to leave the module author feedback so I thought I'd mention it here to see if you might know a way to fix it.

**Comment by crash1115** [comment]
Hey thanks for the feedback! This is my preferred place for it, so that works out great :)

MyBeyond isn't currently a supported module, but I can look into adding support in the next release. I don't have a timeline on when that'll be just yet since the scope of the update is pretty big, but I'm hoping sometime within the next month or so.

**Comment by kaihangaverdener** [comment]
Thanks for the quick response and great to hear you'll be adding improvements. I might look for a different sheet in the meantime as the Downtime tracker adds more depth to characters which I think is something my group would enjoy.

**Comment by crash1115** [comment]
Good news! Should work great in the upcoming update (v0.6.0), coming soon. Sorry it took so long to get to it; life's been pretty crazy. Here's a sneak peek to hopefully make it up to ya!

![image](https://user-images.githubusercontent.com/41387713/118236082-a2bd2980-b463-11eb-8544-9b641e879730.png)
