### ISSUE TITLE
Feature Request: Dice Roll for Increment

### ISSUE THREAD

**Issue by stevecosta** [crash1115/5e-training#58]
Fantastic module. I've been using it track crafting for my players, I'm trying to implement a method for crafting where there's a DC check, followed by a dice roll (which varies on the difficulty of the item) for the item's progress. Could it be possible to add an additional optional field (of String type), that if used would be a dice roll (ex d100) / integer used to increment progress for all progression types?

**Comment by crash1115** [comment]
Hey, thanks for getting in touch! This is a little bit of an odd request, and it's one I'll have to think about whether or not I want to implement.

I say it's odd not because it's an uncommon use case, but because I'm not entirely certain the slight increase in ease of use will outweigh the amount of hacking I have to do behind the scenes to get such a field to work. One of the things I try to do is make sure that every field in the configuration menu is absolutely, transparently clear as far as what it does and what impacts it will have. Something like this, where it's functionality could be changed depending on the type of activity, is inherently unclear.

I'm not sure there's a good way to solve that problem at the moment, so I'll have to think on it. This might get rolled into my thoughts about providing alternative ways of defining how much an activity gets increased by. So you could do things like, "if skill check > dc, increase by 1d10" rather than the current "if skill check > dc, increase by 1". Something like that is a ways down the line, though, if it comes at all.

If you need a fix in the meantime, you can accomplish this sort of thing using the Macro activity type fairly easily. I can whip something up to show you how to go about it, if you want. 😄

**Comment by crash1115** [comment]
Here's how you'd set it up!

![image](https://user-images.githubusercontent.com/41387713/123872066-876a8880-d902-11eb-9ff4-996436376170.png)

And here's the macro:
```js
/*
  This is a sample macro for use with Crash's Tracking & Training.
  It rolls a skill check for a given actor against a DC.
  If the check is successful, it rolls another die and increases
  the value of the activity's progress by that amount.
*/


// ======= CONFIG ========

let actorName = `Test Doggo`; //The name of the actor who owns the activity to update.
let itemName = `Crafting Example`; // The name of the activity to update.
let checkDc = 15; // The DC of the check
let skillToRoll = `med`; // The abbreviation of the skill to roll.
let increaseBy = `1d10`; // The die roll to increase the progress by if the check succeeds.

// ==========================

// Get our actor and item
let item = CrashTNT.getActivity(actorName, itemName);
let actor = game.actors.getName(actorName);

// Make necessary rolls
let skillRoll = await actor.rollSkill(skillToRoll);
let total = skillRoll.total;

// If total is high enough, roll and increase progress
if(total >= checkDc){
    let increaseRoll = await new Roll(increaseBy).toMessage();
    let increase = increaseRoll._roll._total;
    let newProgress = item.progress + increase;
    CrashTNT.updateActivityProgress(actorName, itemName, newProgress);
}
```

**Comment by stevecosta** [comment]
Thanks @crash1115, I'll give it a try. If you'd like, I could try a PR to let you comment and test out the concept but I totally respect your design and architecture decisions. Thank you again for the macro!

**Comment by crash1115** [comment]
Closing because the functionality is attainable using macro activities, and I've decided the work/payoff isn't worthwhile.
