### ISSUE TITLE
PF1e Support

### ISSUE THREAD

**Issue by crogonint** [crash1115/5e-training#66]
Greetings!

I hate to be 'that guy' but this sort of module DOES seem like it could be rather platform independent. People have been asking for a downtime module for PF 1st. Ed. Is there any way you could just snip this out of 5th Ed. and make it a universal module? ..or make another one that is?

I'm sure that you would be a better judge of whether this would be a fairly simple task, or a living nightmare. I wouldn't even ask, but it does seem like something like this would be fairly easy to make in to a universal sort of module.

If it would be easier to plug it in to PF 1st. Ed. (which is basically DnD 3.5) for some reason, I'd be happy to collect data for integration and etc. I mean, I could even attempt the coding myself.. but it's been a few decades. ;)

**Comment by crash1115** [comment]
I think this is a valid request, and de-coupling the module from 5e is something that I've thought about in the past. Unfortunately it's one of those things that falls into the "living nightmare" category, but not because of how difficult it may or may not be to implement using code.

The real blocker for me with either porting this to another system or making it a generic module, is that in order to do that, I need to figure out things like:

- How does this system handle rolls? Are there even rolls at all?
- What rolls would a person using this system reasonably need to make?
- What sorts of things would a person using this system want to keep track of?
- What tools can I provide that help make those common use cases more user friendly?
- What does the character sheet look like, and what do I have to modify about my implementation to make it work on the new sheet?
- Is there actually demand here, and can I realistically handle dedicating time to helping this new pool of users?

For every single system I want to support. A lot of the times, the answers to those questions will necessitate fairly low amounts of re-work to existing code or creation of new code. However, the last one is a killer. The broader I make this project in scope, the more time I need to spend working on fixing bugs, maintaining (potentially duplicate) code, and keeping on top of new system developments so I can make sure things keep working. That in itself probably isn't too bad until you start factoring in this really big, slippery slope of, "Hey you supported System X, can you support System Y?" and then the amount of time I'm spending on this thing starts growing by a lot more than I intended it to.

At some point, I have to draw a line, and that's not going to be fair to someone. So I'm drawing it now. It really kinda sucks, because I'd love to be able to bring this to more people who can use it. I'm with you 100% when you say this seems like it could be pretty generic, and I have had a number of people come and ask me about PF1e support. It's just not in the cards for me right now.

That said, if you wanna fork this repo and take a crack at re-purposing it for pf1e, you're more than welcome to do so. I can even help you out if you have questions about how my terrible code works and what things do. I might even be persuaded to make a branch here that pulls some of the 5e stuff out and provides a framework for something a little more easily configurable, which you could use as a baseline. But that's about as much support as I can give you on this one.

**Comment by crogonint** [comment]
Well, I would have to disagree with your point of it not being in demand. PF 1st. Ed. is mechanically (basically) identical to D&D 3.5 AND d20. I'd need to see some solid numbers to convince me that there ARE more people playing D&D 5e than those three platforms put together!

None the less, I do understand your reasoning. I'm currently wrapping all of my time up in to building a resource to replace the Dundjinni forums as a source of free assets. If I ever get that to a point to where it runs itself, I'll try to come back here and take a stab at this. Thanks for your time!
