### ISSUE TITLE
Feature Request - Gold/resource consumption

### ISSUE THREAD

**Issue by lucaspicerni** [crash1115/5e-training#76]
Add gold expenditure and resource (item) consumption along with each roll.

**Comment by crash1115** [comment]
Hey thanks for the feature request! This is definitely on my list because a bunch of people have asked for it, but I have no ETA on it since I'm a little burned out on Foundry stuff right now.

If you need a workaround in the meantime, this can be accomplished using items set up with the macro progression type. Not sure how comfortable you are with macros, but I can give you an example to get you going if you'd like.
